name: cicd client web develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - "**"
      - "!.gitignore"
      - "!.editorconfig"
      - "!README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: |
          echo "NEXT_PUBLIC_ENVIRONMENT=development" >> .env.development
          echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env.development
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL_DEVELOP }}
      - uses: actions/cache@v4
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_DEVELOP }}
      - run: ssh-keyscan ${{ secrets.SERVER_IP_DEVELOP }} >> ~/.ssh/known_hosts
      - run: rsync -avz -e "ssh" . ${{ secrets.SSH_USER_DEVELOP }}@${{ secrets.SERVER_IP_DEVELOP }}:~/app/hiel-side-client-web
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP_DEVELOP }}
          username: ${{ secrets.SSH_USER_DEVELOP }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEVELOP }}
          port: 22
          script: |
            cd ~/app/hiel-side-client-web
            pm2 stop hiel-side-client-web
            pm2 start "npm run dev" --name hiel-side-client-web
